### ISSUE TITLE
Error when navigating away from a component using ngxd/core

### ISSUE THREAD

**Issue by st-clair-clarke** [IndigoSoft/ngxd#26]
Hi
I have two lazy loaded modules - registration and preferences. I am using:
1. "@angular/cli": "^9.0.0-rc.6" with similar @angular packages
2. "@ngxd/core": "^8.0.0"
3. Windows 10 environment

The registration modules use ngxd/core  to load forms dynamically into an accordion.

Navigation via a sidebar from /preferences to /registration is fine. However, navigating from the /registration to /preferences crashes the application with the following errors:

`
core.js:6382 ERROR Error: Uncaught (in promise): TypeError: Cannot delete property 'hasIcon' of [object Object]
TypeError: Cannot delete property 'hasIcon' of [object Object]
    at HostInputAdapter.dispose (ngxd-core.js:183)
    at HostInputAdapter.detach (ngxd-core.js:161)
    at HostAdapter.detachInput (ngxd-core.js:243)
    at NgxComponentOutletAdapterRef.detachHostInput (ngxd-core.js:390)
    at NgxComponentOutletAdapterRef.disposeInputs (ngxd-core.js:487)
    at NgxComponentOutletAdapterRef.dispose (ngxd-core.js:304)
    at NgxComponentOutletDirective.destroyAdapterRef (ngxd-core.js:798)
    at NgxComponentOutletDirective.ngOnDestroy (ngxd-core.js:777)
    at executeOnDestroys (core.js:16128)
    at cleanUpView (core.js:16036)
    at resolvePromise (zone-evergreen.js:793)
    at resolvePromise (zone-evergreen.js:752)
    at zone-evergreen.js:854
    at ZoneDelegate.invokeTask (zone-evergreen.js:400)
    at Object.onInvokeTask (core.js:41410)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Zone.runTask (zone-evergreen.js:168)
    at drainMicroTaskQueue (zone-evergreen.js:570)
`

Seems as if icons are being deleted.
What do you think? Looking forward to hearing from you. Thanks.

**Comment by thekiba** [comment]
Hello! Please, let me an example how you're using ngxd in the component. And then I'll try to help.

**Comment by st-clair-clarke** [comment]
The following is my actual usage - it will not run if you cut and paste because of imports, but the general code can be seen.

**MattExpansionPanelComponent**

`
import {
  ChangeDetectionStrategy, Component, EventEmitter, Input, OnDestroy, Output
} from '@angular/core'
import { SharedAppDataService } from '@pim/common/core'
import { FormState, IFormState } from '@pim/common/store'
import { messages } from '@pim/common/validation-model'
import { AutoUnsubscribe } from 'ngx-auto-unsubscribe'

@AutoUnsubscribe()
@Component(
  {
    selector: 'matt-expansion-panel',
    changeDetection: ChangeDetectionStrategy.OnPush,
    template: `
      <mat-expansion-panel
          [expanded] = "step === row"
          (opened) = "setStep(row)"
          hideToggle>
        <mat-expansion-panel-header>
          <mat-panel-title>

            <pim-nhncd-mat-icon
                [color] = '"accent"'
                [svgIcon] = 'titleIcon'>
            </pim-nhncd-mat-icon>

            <pim-nhncd-label
                [labelMarginLeft] = '"5px"'
                [labelMarginRight] = '"5px"'
                [labelMarginTop] = 'labelMarginTop'
                [lable] = 'lable'
                class = 'bold'></pim-nhncd-label>

            <pim-nhncd-mat-status-icon
                [dirty] = 'dirty'
                [valid] = 'valid'
                [top] = 'statusIconTop'></pim-nhncd-mat-status-icon>
          </mat-panel-title>

        <ng-template
            #inputCmp
            *ngIf = 'component'
            matExpansionPanelContent>

          <ng-container
              [ngxComponentOutlet] = 'component'
              (ngxComponentOutletActivate) = "onActivate($event)">
          </ng-container>

          <mat-action-row>
            <button
                *ngIf = "row == 0 && maxRows == 1"
                mat-button
                color = "primary"
                (click) = "nextStep()">Close
            </button>

            <button
                *ngIf = "row == 0 && maxRows > 1"
                mat-button
                color = "primary"
                (click) = "prevStep()">Next
            </button>

            <button
                *ngIf = "row == 1 && maxRows ==2"
                mat-button
                color = "warn"
                (click) = "prevStep()">Previous
            </button>

            <button
                *ngIf = "row == 1 && maxRows > 2"
                mat-button
                color = "primary"
                (click) = "nextStep()">Next
            </button>

            <button
                *ngIf = "maxRows == '-1'"
                mat-button
                color = "warn"
                (click) = "prevStep()">Previous
            </button>
          </mat-action-row>

        </ng-template>
      </mat-expansion-panel>
    `,
    styles: []
  } )
export class MattExpansionPanelComponent implements OnDestroy {
  @Input() component: any
  @Input() description = messages.error.formError
  @Input() dirty = false
  @Input() labelMarginTop = '4px'
  @Input() lable = { row1: 'Label', axis: 'column' }
  @Input() options: any
  @Input() state: Partial<IFormState> = new FormState()
  @Input() valid = false
  @Input() statusIcon = ''
  @Input() statusIconTop = '0px'
  @Input() target: string
  @Input() titleIcon = 'question-l1'
  @Input() titleIconTop = ''
  @Output() eventData = new EventEmitter<Partial<IFormState>>()
//  @Input() index = 0
  @Input() maxRows = 0
  @Input() row = 0
  step = 0
  
  constructor( public store: SharedAppDataService ) {}
  
  ngOnDestroy() {
    // needed for @AutoUnsubscribe()
  }
  
  onActivate( component: any ) {
    this.state.target = this.target
//    this.state.options[ 'component' ] = component
    this.eventData.emit( this.state )
  }
  
  setStep( row: number ) {
    this.step = row
  }
  
  nextStep() {
    this.step++
  }
  
  prevStep() {
    this.step--
  }
}

`

**nok.component.html**

`
  <pim-nhncd-mat-expansion-panel
      [component] = 'genderCmp'
      [dirty] = 'genderState["dirty"]'
      [lable] = "{ row1: 'Gender', axis: 'column', star: true }"
      [maxRows] = '4'
      [row] = '3'
      [valid] = 'genderState["valid"]'
      [target] = '"[gender->nok]cmp"'
      titleIcon = 'gender-male-female'></pim-nhncd-mat-expansion-panel>
</mat-accordion>
`

Thanks

**Comment by thekiba** [comment]
Where you're using `hasIcon` property? Can you show me that component too?

**Comment by st-clair-clarke** [comment]
The first component dynamically injected by ngxd/core is NameComponent with the following ..

`export class NameComponent implements OnInit {
  @Input() hasIcon = false
  @Input() size = '25'
  @Input() target = ''
  @Output() event = new EventEmitter<IFormState>()
  controls: Object
  form: RxFormGroup
  middle: AbstractControl
  name: IName = new Name()
  state: Object
  suffixFilteredOptions$: Observable<Array<string>>
  suffixOptions: string[]
  titleGroupOptions: Observable<IGroupedOptions[]>
  titleGroups: IGroupedOptions[]`
Now, when I commented out the hasIcon property, the error then points to the next Input property size - so it seems that the Input() properties are the problem.

**Comment by st-clair-clarke** [comment]
Note that without navigating from the /registration url, everything is fine, and the component is displayed. I only found out the error when I added the /preferences route and navigate away from /registration that generates the errors.

**Comment by thekiba** [comment]
Seems interesting, because I had tried to reproduce the problem on stackblitz and I doesn't see something error.

Maybe can you try to do it? https://stackblitz.com/edit/angular-simple-dynamic-ptv1e4

**Comment by thekiba** [comment]
I had update this demo, please check this again. If you can fix it and show the problem, then I will be able to help you.

Otherwise, you can try to create different component for using *ngxComponentOutlet and try again.

**Comment by st-clair-clarke** [comment]
How do you navigate the stackblitz examaple.

**Comment by f1ght4fun** [comment]
I have exactly same issue.

on dispose method, when it tries to delete  input  - throws "Cannot delete property 'XXX' of [object Object]   at HostInputAdapter.dispose

**Comment by thekiba** [comment]
@st-clair-clarke @f1ght4fun could you please reproduce the problem on the Stackblitz?

**Comment by f1ght4fun** [comment]
for some reason your stackblitz doesn't even render anything for me now. 
issue happens when i want to pass via context input/output properties which doesn't seem to be happening now

**Comment by thekiba** [comment]
@f1ght4fun @st-clair-clarke could you please check your issue with @ngxd/core@9.0.3? Let me know if all ok or not.

**Comment by thekiba** [comment]
I think that similar problem with #29 https://github.com/IndigoSoft/ngxd/issues/29#issuecomment-588397911

Please, let me know if that issue still not resolved.
