### ISSUE TITLE
ngOnDestroy doesn't get called on child component when changing to a different one

### ISSUE THREAD

**Issue by jpike88** [IndigoSoft/ngxd#27]
I'm guessing this is incorrect behaviour?

If not, is there another way to detect when this occurs in the child component, as it may need reinitialisation?

**Comment by thekiba** [comment]
Hello @jpike88! NgOnDestroy should be always called on child components when destroyed or we change to another one.

So, can you reproduce that issue on Stackblitz? You could use this as template https://stackblitz.com/edit/angular-simple-dynamic

**Comment by jpike88** [comment]
dont worry its an issue with my own implementation never mind
