### ISSUE TITLE
Lazy loaded dynamic components requires Ivy compiler enabled

### ISSUE THREAD

**Issue by ctaleck** [IndigoSoft/ngxd#40]
It seems to me that a great use-case for dynamic components in Angular is to lazy load multiple components, especially from separate Angular Libraries. I want use the [animals example](https://stackblitz.com/edit/angular-simple-dynamic?file=src/app/app.module.ts) with the [lazy resolve technique](https://stackblitz.com/edit/angular-ivy-ngxd-lazy-resolver-simple-demo?file=src/app/app.component.ts). 

Here is my [forked Stackblitz](https://stackblitz.com/edit/angular-simple-dynamic-hafygp?devtoolsheight=33&file=src/app/app.component.ts), however, I receive an error.

    ERROR Error: No component factory found for LazyDogDynamic. Did you add it to @NgModule.entryComponents?

No matter where I add `entryComponents`, I still get the error. How do I get a working example using these two techniques? Sorry, the readme documentation does not provide enough details on lazy loading.

**Comment by thekiba** [comment]
👋 Hey, @ctaleck! 

You have to Enable Ivy in the left side menu, and then dynamic components will be loaded lazily and work fine.

![image](https://user-images.githubusercontent.com/1910515/134499511-0df676f4-c12c-4cb3-bfcf-340bd7047591.png)
