### ISSUE TITLE
Add support for Angular 16

### ISSUE THREAD

**Issue by shmasya** [IndigoSoft/ngxd#60]
### Describe the feature you would like to see added
Add support for Angular 16

### Describe the solution you'd like
Update peer dependencies to allow angular 16:
```json
"peerDependencies": {
    "@angular/common": "^15.0.0",
    "@angular/core": "^15.0.0",
    "rxjs": ">=6.0.0"
}
```
### Describe alternatives you have considered
1. Keep on old angular
2. Force update anyway and run "npm install --force" every time

**Comment by thekiba** [comment]
@shmasya Thank you for your issue request. I'm pleased to announce that the latest version of @ngxd/core, version 16.0.0, now fully supports Angular 16. I appreciate your interest in improving our library. If you encounter any problems or have suggestions for further enhancements, please don't hesitate to share.
