### ISSUE TITLE
Context available only OnChanges and not OnInit

### ISSUE THREAD

**Issue by ciukstar** [IndigoSoft/ngxd#7]
Here is my template:
```
<mat-accordion>
  <mat-expansion-panel *ngFor="let sc of showcases;let i = index;" [expanded]="i === 0">
    <mat-expansion-panel-header>
      <mat-panel-title>{{sc.name}}</mat-panel-title>
      <mat-panel-description>{{sc.description}}</mat-panel-description>
    </mat-expansion-panel-header>
    <ng-template matExpansionPanelContent>
      <ng-container
        *ngxComponentOutlet="components.get(sc['component'])['component'];
                             context: components.get(sc['component'])['context'](sc)|async">
      </ng-container>
    </ng-template>
  </mat-expansion-panel>
</mat-accordion>
```
where `components: Map<string, { component: Type<any>; context: (x: ChartTemplate) => Observable<any> }>`

The values (bindings) that `context` provides is available only in `ngOnChanges` and NOT in `ngOnInit` nor in `ngAfterInit`. That is not o problem until there is a `MatSnackBar` that needs info from `context` and if opened from `ngOnChanges` gives `ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'role: undefined'. Current value: 'role: alert'. It seems like the view has been created after its parent and its children have been dirty checked. Has it been created in a change detection hook ?`

**Comment by thekiba** [comment]
Can you repeat the error on stackblitz.com and send a link here?

**Comment by ciukstar** [comment]
https://stackblitz.com/edit/angular-tvy512

The problem arises when emitted values are delayed. Check console.

**Comment by thekiba** [comment]
Hello, i'm trying repeat error, but seems be ok

![image](https://user-images.githubusercontent.com/1910515/49303805-b8c91080-f4db-11e8-8b7b-0e48298d7e89.png)

**Comment by ciukstar** [comment]
Expected output would be:

```
Angular is running in the development mode. Call enableProdMode() to enable the production mode.
FirstComponent: ngOnChanges: a: value for first
FirstComponent: ngOnInit: a: value for first
FirstComponent: ngAfterViewInit: a: value for first
SecondComponent: ngOnChanges: a: value for second
SecondComponent: ngOnInit: a: value for second
SecondComponent: ngAfterViewInit: a: value for second
```
(Not sure about `ngOnChanges` on first load, maybe `a: undefined`)
Anyway, this result can be achieved by wrapping `*ngxComponentOutlet` with `*ngIf` like so:

```
<div *ngFor="let t of tmpls">
  <ng-container *ngIf="(components.get(t['component'])['context'](t) | async) as ctx; else loading">
    <ng-container
      *ngxComponentOutlet="components.get(t['component'])['component']; context: ctx;">
    </ng-container>
  </ng-container>
</div>
<ng-template #loading>
  Loading...
</ng-template>
```

**Comment by ciukstar** [comment]
The problem can be resolved by wrapping `*ngxComponentOutlet` with an `*ngIf`
